project:
  type: website
  output-dir: docs
  resources: 
    - DANIEL_ODUNSI.pdf

website:
  favicon: Business_Favicon.png
  page-footer: 
    left: "Copyright 2025, Daniel Odunsi"
  navbar:
    logo: Business_Favicon.png
    right:
      - href: index.qmd
        text: Home
      - href: DANIEL_ODUNSI.pdf
        text: CV
        target: _blank
      - href: Projects.qmd
        text: Projects
      - href: Job experience.qmd
        text: Job Experience
      - href: College.qmd
        text: College
      - href: about.qmd
        text: Hobbies
      - href: Reflection.qmd
        text: Reflection
      
format:
  html:
    theme:
      light: lux
      dark: solar
    css: styles.css
    toc: false
    page-layout: full
    breadcrumbs: false

