project:
  type: website
  output-dir: docs

website:
  favicon: Business_Favicon.png
  page-footer: 
    left: "Copyright 2025, Daniel Odunsi"
  navbar:
    logo: Business_Favicon.png
    right:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: Projects/Business_Strategy.qmd
            text: Business Strategy
          - href: Projects/NED.qmd
            text: NED
      - href: Job experience.qmd
        text: Job Experience
      - href: College.qmd
        text: College
      - href: about.qmd
        text: Hobbies
        

sidebar:
  - title: Projects
    contents: 
      - Projects
      - section: Projects
        contents:
         - Projects/Business_Strategy.qmd
         - Projects/NED.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full
