project:
  type: website
  output-dir: docs

website:
  title: "Daniel Odunsi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - Job experience.qmd
      - College.qmd
      - Projects.qmd
      - about.qmd
  
sidebar:
  - title: Projects
    contents: 
    - Projects/NED.qmd
    - Projects/Business_Strategy.qmd


format:
  html:
    theme: trestles
    css: styles.css
