project:
  type: website
  output-dir: docs
  resources:
    - images/*
    - Videos/*
    - Experience/*
    - DANIEL_ODUNSI.pdf
    - Strat_report

website:
  favicon: Business_Favicon.png
  page-footer: 
    left: "Copyright 2025, Daniel Odunsi"
  navbar:
    logo: Business_Favicon.png
    right:
      - href: index.qmd
        text: Home
      - href: DANIEL_ODUNSI.pdf
        text: CV
        target: _blank
      - href: Projects.qmd
        text: Projects
      - href: Job experience.qmd
        text: Job Experience
      - href: about.qmd
        text: Hobbies
      - href: Contact.qmd
        text: Contact me
      - href: Reflection.qmd
        text: Reflection
      
format:
  html:
    theme:
      light: lux
      dark: solar
    css: styles.scss
    toc: false
    page-layout: full
    breadcrumbs: true


