project:
  type: website

website:
  title: "Lecture-9-test"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects/Index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



